### ISSUE TITLE
图片来源

### ISSUE THREAD

**Issue by concept-agi** [williamliujl/Qilin-Med-VL#1]
作者你好，我想请教一下，图片的来源问题。
我观察到ChiMed-VL-Alignment.jsonl中，只有263,175个样本（图像文本对），和介绍中的580,014 image-text不一致，请问你们是只发布了其中一部分数据吗？另外，你们会发布你们数据集中的图片数据吗？

**Comment by williamliujl** [comment]
你好

1. 目前我们公布了PMC-OA部分的数据，PMC-CaseReport部分的数据后续会开源。
2. 2. 图像数据我们暂时不会发布。

感谢对我们工作的关注

**Comment by SupritYoung** [comment]
插眼，期待发布～
